<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="manjit-Vostro-1015" name="Revision.HardAndSoftAsert" tests="2" failures="1" timestamp="09 Feb 2019 06:11:32 GMT" time="34.781" errors="0">
  <testcase name="hardtest2" time="13.255" classname="Revision.HardAndSoftAsert">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [KSRTC Official Website for Online Bus Ticket Booking] but found [KSRTC Official Website for Online Bus Ticket Booking - KSRTC.in]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [KSRTC Official Website for Online Bus Ticket Booking] but found [KSRTC Official Website for Online Bus Ticket Booking - KSRTC.in]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at Revision.HardAndSoftAsert.hardtest2(HardAndSoftAsert.java:56)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- hardtest2 -->
  <testcase name="hard" time="21.526" classname="Revision.HardAndSoftAsert"/>
</testsuite> <!-- Revision.HardAndSoftAsert -->
